### ISSUE TITLE
The initial value for input "*******" is missing. 

### ISSUE THREAD

**Issue by agonzalezcr** [wsmd/react-use-form-state#106]
Hi there,

First of all thanks a lof for this amazing library. I have a question and not sure if I'm doing something wrong. But I'm using the {raw} type and keep getting the:

_The initial value for input "inputName" is missing. Custom inputs controlled with raw() are expected to have an initial value provided to useFormState(). To prevent React from treating this input as uncontrolled, an empty string will be used_ 

My form state looks like:

`const [formState, { raw }] = useFormState({
    inputName : input.initialValue || ""
  });`

And my custom component looks like:

`<CustomComponent
        {...raw({
          name: 'inputName',
          validate: myValidateFunc
        })}
      />`

I have tried passing the value after the validate attribute, but I keep getting the same error.

Any clues ?

**Comment by hshelbur** [comment]
I'm having a similar issue setting the initial value of a raw input using react-select, I'm not having the error show but the initial value is undefined

**Comment by wsmd** [comment]
Hi @agonzalezcr - any chance you could provide a working example that replicates the issue?

Here's a template that you fork: https://codesandbox.io/s/smoosh-night-q3h8i?expanddevtools=1
