### ISSUE TITLE
Suggestion: password masking visibility toggle

### ISSUE THREAD

**Issue by mirshko** [wsmd/react-use-form-state#107]
Loving the package so far! Just wondering if there was some way there could be a built in function for the password field to toggle the visibility of the password. It seems the easiest way to do it would be use a text input and then toggle the type manually via a prop, but it might be nice to just have a function on the password type to toggle it in the API. 

It seems password toggles are better for UX and it would be nice to have it all built into this awesome package.

**Comment by wsmd** [comment]
Hi @mirshko - this seems to be outside the scope of this library as it's only intended to help with managing the form state, not necessarily how they look. There's probably a way to achieve this perhaps using `.raw()`.

```jsx
function MaskedPassword(props) {
  return (
    // MaskedPassword implementation
  )
}

function MyForm() {
  const [formState, { raw }] = useFormState({ password: '' });
  return (
    <>
      <MaskedPassword {...raw('password')} />
    </>
  )
}
```

I suggest taking a look at the [Custom Controls](https://github.com/wsmd/react-use-form-state#custom-controls) section of the documentation for more information.
