### ISSUE TITLE
Nested objects support

### ISSUE THREAD

**Issue by andrey-shabalin** [wsmd/react-use-form-state#119]
It will be nice to have ability to use nested objects with setting the path to field in name property.
Something like this: 
```
import { useFormState } from 'react-use-form-state';

export default function BeesForm({ onSubmit }) {
  const [formState, { text }] = useFormState({
      bees: [{ name: 'Jack' }, { name: 'Jon'} ],
      nests: {
          someID: {
             name: 'first'
          }
      }
  });

  function handleSubmit(e) {
    // ...
  }

  return (
    <form onSubmit={handleSubmit}>
      {
        formState.values.bees.map((bee, index) =>  <input {...text(`bees[${index}].name`)} />)
      }
      <input {...text('nests.someID.name]')} />
     </form>
  );
}
```

we could use `_.set/_.get` from **lodash** for that.

**Comment by wsmd** [comment]
Hi @andrey-shabalin - I don't know if that's a use case this library would be able to support. 

That said, I'm curious if have you looked into the `raw` option (https://github.com/wsmd/react-use-form-state#custom-controls). This option allows you to build custom controls that their value could be anything including nested objects.
