### ISSUE TITLE
validate that fields match 

### ISSUE THREAD

**Issue by keeganstothert** [wsmd/react-use-form-state#121]
I cannot validate that two fields match (password/verify password, etc) because the validators are only run for the individual fields. Is there a way to trigger validation across all fields or even to manually set invalid state so i can manage it myself?

this would be great, 
`setFieldValidity('fieldName', false)`

**Comment by keeganstothert** [comment]
my current workaround is to add the validation logic to both fields and the invalid field will just have to be the last one that was touched

**Comment by wsmd** [comment]
Hi @keeganstothert – I don't believe it's currently possible to trigger validation across all fields because validation requires a change/blur event that is only available when a user interact with a form. This library also falls back to HTML5 validation if a custom validate function isn't specified, but that also (currently) requires access to the DOM node which is only accessible via the change/blur event itself.

That said, I think it might actually possible to expose something like `setFieldValidity` so that you can manage the validation state manually! I'll look into that soon! 👍 In the meantime, could you please give me an example of how something like `setFieldValidity` would solve your use case (validating matching fields)?

**Comment by keeganstothert** [comment]
sure!

first, I wrap your library to provide debouncing and a custom validation.

```js
import { useMemo, useCallback, useState } from 'react';
import useDebounce from 'hooks/utilities/useDebounce';
import { useFormState } from 'react-use-form-state';

export default function useDebouncedForm(initialValues) {
  const [formState, primitives] = useFormState(initialValues);
  const [validators] = useState({});
  const values = useDebounce(formState.values, 500);
  const setValidator = useCallback(() => {
    return (field, validator) => {
      validators[field] = validator;
    };
  }, [validators]);
  const debouncedForm = useMemo(() => {
    return {
      values,
      validators,
      setValidator,
      touched: formState.touched,
      setField: formState.setField,
    };
  }, [formState.setField, formState.touched, values, setValidator, validators]);

  return [debouncedForm, primitives];
}

```

I use one hook to check for required fields and another to run my validators. The fields are checking to see if their flag is set and they display popover until the timeout clears the flag. I do this so i can check for missing fields and mismatched fields (password & verifyPassword) and prevent the form from submitting 

```js
import { useState, useCallback } from 'react';

export default function useValidateForm({ formState, requiredFields, run }) {
  const [missingFields, setMissingFields] = useState(new Set());

  const submit = useCallback(() => {
    const missing = requiredFields.filter(key => !formState.values[key]);

    if (missing.length > 0) {
      setMissingFields(new Set(missing));
      setTimeout(() => {
        setMissingFields(new Set());
      }, 3500);

      return;
    }

    run();
  }, [formState.validators, formState.values, requiredFields, run]);

  return { missingFields, invalidFields, submit };
}

```

with `setFieldValidity` I think i could go back to using your in built validation api and set missing fields manually. The best api would also allow us to re-run the validate function we provided initially `{...text({ name: 'someField', validate: val => checkVal(val)})` or optionally pass something different. it would also be great to get all field values `setFieldValidity('someField', (value, values) => checkValidity(value, values))`
