### ISSUE TITLE
setField should not be packaged with formState

### ISSUE THREAD

**Issue by keeganstothert** [wsmd/react-use-form-state#124]
```js
useEffect(() => {
formState.setField('somefield', someValue)
}, [formState, formState.setField])
```

the formState is automatically added as a dependency which causes an infinite loop. i can destructure...

`const {setField} = formState`

but it seems like setters should be seperated from state to prevent infinite loops, maybe...

`const [formState, {text, raw}, { setField }] = useFormState()`

this should include all functions that modify the state including future ones like `setValidity()`!

**Comment by wsmd** [comment]
@keeganstothert (cc @dcousens) I'm not able to reproduce the issue. What version are you using? are you using the latest?

**Comment by dcousens** [comment]
@wsmd I recant;  I was confusing this with https://github.com/wsmd/react-use-form-state/issues/105 (which has been resolved).
