### ISSUE TITLE
<select multiple> support

### ISSUE THREAD

**Issue by samholmes** [wsmd/react-use-form-state#13]
Either I'm missing the explanation on how to do this, but it seems as though it's currently not possible to create a select form element with a multiple attribute. Maybe an additional `input.selectMultiple` function should be added?

**Comment by wsmd** [comment]
Hi @samholmes,

Thanks for the issue! That's correct. It's currently not possible but it's on my todos! I just haven't had a chance to work on it yet.

https://github.com/wsmd/react-use-form-state/blob/14e3cd7d40294ecd2672e039f3897a0e3bb235fb/src/constants.js#L22-L24

I should be able to revisit this very soon!  😄
