### ISSUE TITLE
Reference Nested Values with Name

### ISSUE THREAD

**Issue by mdreyer** [wsmd/react-use-form-state#131]
I didn't see anything in anything documented about this, nor any open issues addressing this - is there a way to reference nested values with a field's `name`?

i.e. if I have this object that I want to represent with my form:

```
{
  someRootField: {
    someNestedField: [
      { theFieldImAfter: theValueImAfter }
    ]
  }
}
```

I'd expect to be able to reference `theValueImAfter` with something like:

```
const [formState, { checkbox }] = useFormState({});

// ..

<Checkbox
  {...checkbox(
    name="someRootField.someNestedField[0].theFieldImAfter"
  )}
/>
```

but this just adds a new field to `formState` called "someRootField.someNestedField[0].theFieldImAfter"

**Comment by wsmd** [comment]
Hi @mdreyer! Please refer to https://github.com/wsmd/react-use-form-state/issues/119#issuecomment-555127306 for more information.
