### ISSUE TITLE
isPristine feature is not present in dist package

### ISSUE THREAD

**Issue by mpfullstack** [wsmd/react-use-form-state#134]
Hello,

I just started using your package, very good one, thanks. But I found out that isPristine feature is not present in the code donwloaded from NPM 

https://registry.npmjs.org/react-use-form-state/-/react-use-form-state-0.12.1.tgz

Is it right or am I missing something here?

Thank you very much

**Comment by wsmd** [comment]
Hi @mpfullstack – `isPristine` has not been published yet.

The documentation for 0.12.1 is available here:
https://github.com/wsmd/react-use-form-state/blob/0.12.1/README.md

`isPristine` should be coming soon with 0.13.0 (it's an overdue update tbh, but I have been busy lately! 😅  stay tuned!)

**Comment by wsmd** [comment]
Oh I forgot to mention that `isPristine` is available in the beta release! `react-use-form-state@beta`. Feel free to use it in the meantime!

**Comment by mpfullstack** [comment]
Oh ok, I see.

Thank you very much for the info.

**Comment by DanielTamkin** [comment]
Any update on this? Just ran into the same thing too since it's in the `README` 😅.
If you need help implementing this I'd love to help out if needed.

**Comment by wsmd** [comment]
0.13.0 is now available on npm! 😄
