### ISSUE TITLE
Raw inputs are not given a `name` prop

### ISSUE THREAD

**Issue by markerikson** [wsmd/react-use-form-state#141]
The TS typedefs say that `RawInputProps` includes a `name` field:

https://github.com/wsmd/react-use-form-state/blob/16df9001b6e390fa0957b09979e2bd39d41c3862/src/index.d.ts#L132-L137

However, that `name` field is not currently included in the props object:

https://github.com/wsmd/react-use-form-state/blob/16df9001b6e390fa0957b09979e2bd39d41c3862/src/useFormState.js#L310-L316

Can we get that field added in to match the typedefs?

**Comment by wsmd** [comment]
Should be now fixed in 0.13.2
