### ISSUE TITLE
useFormState API change suggestion

### ISSUE THREAD

**Issue by emlai** [wsmd/react-use-form-state#25]
Currently the suggested use of this API is as follows:

```tsx
  const [formState, { text, email, password, radio }] = useFormState();
  return (
    <form onSubmit={() => console.log(formState)}>
      <input {...text('name')} />
      <input {...email('email')} required />
      <input {...password('password')} required minLength="8" />
      <input {...radio('plan', 'free')} />
      <input {...radio('plan', 'premium')} />
    </form>
  );
```

What I don't like about this is the duplicated `{ text, email, password, radio }` list. You have to repeat every input type you're using there. When you add or remove inputs in your form you possibly have to edit this list. I think adding or removing inputs should only involve adding/removing the `<input>` line.

To achieve that we can use the current API as follows:

```tsx
  const [formState, inputs] = useFormState();
  return (
    <form onSubmit={() => console.log(formState)}>
      <input {...inputs.text('name')} />
      <input {...inputs.email('email')} required />
      <input {...inputs.password('password')} required minLength="8" />
      <input {...inputs.radio('plan', 'free')} />
      <input {...inputs.radio('plan', 'premium')} />
    </form>
  );
```

At this point, it seems to make sense to combine `formState` and `inputs` so that `useFormState` returns only one object:

```tsx
  const form = useFormState();
  return (
    <form onSubmit={() => console.log(form.state)}>
      <input {...form.text('name')} />
      <input {...form.email('email')} required />
      <input {...form.password('password')} required minLength="8" />
      <input {...form.radio('plan', 'free')} />
      <input {...form.radio('plan', 'premium')} />
    </form>
  );
```

This also makes it clear which form each input belongs to, if you happen to have multiple forms within the same component.

I think this would be a nicer API. What do you think? 

I know this would be a breaking change so I understand if you're not willing to implement this.

**Comment by wsmd** [comment]
Hi @emlai 

> At this point, it seems to make sense to combine formState and inputs so that useFormState returns only one object:

It's hard for me to see a big different between the following:

```ts
// this
const form = useFormState();
// vs
const [state, form] = useFormState();

<input {...form.text('name')} />
<input {...form.email('email')} required />
<input {...form.password('password')} required minLength="8" />
<input {...form.radio('plan', 'free')} />
<input {...form.radio('plan', 'premium')} />
```

In both of your examples above, the inputs are still name spaced, so the difference is only with destructuring the array `[state, ____] =` into two variables, which I don't see as a big difference.

That said, I will take into consideration for the `1.0.0` release as I'm planning on adding new features and API design changes in the future.

Thanks!
