### ISSUE TITLE
reset form

### ISSUE THREAD

**Issue by PlayMa256** [wsmd/react-use-form-state#33]
Hello!
Is there an easier way to cleanup the state? It would be good to have it specially when you submit the form.

**Comment by wsmd** [comment]
Hi @PlayMa256! There isn't currently a way to reset the form state, but I'm planning on adding that in the next release `0.9.0`.

For the time being, although depends on your use-case, a less-than-ideal workaround is to leverage the React's `key` to cause the form to re-render, though might not work for every use case.

Consider the following example: https://codesandbox.io/s/x3kznwm6lo

**Comment by freemember007** [comment]
+1, 
can not give formState object a 'clear' medthod ?

**Comment by bfillmer** [comment]
@wsmd Saw you moved this to **0.10.0**, need help with it or is it _almost ready_?

**Comment by wsmd** [comment]
hey, @bfillmer - It's all good! I moved this to `0.10.0` so that I don't delay the 0.9.0 release. This has some overlap with #52 so I'm trying still to find a good balance between the two. I'm playing around with some ideas.
