### ISSUE TITLE
Supported number type for FormValue? 

### ISSUE THREAD

**Issue by hibado** [wsmd/react-use-form-state#36]
When my form values includes some number, the editor report 'type number is not assignable to string'. The code like this: 
```
type FormValues = { status: number[] }
const [{ values }, { radio }] = useFormState<FormValues>({ status: [0, 1, 2, 3] }) // can not be assigned
```
The declaration file may not support the number type. Consider about supports, or any other solution?

**Comment by wsmd** [comment]
Hi @hibado, 

I think in your example above you meant to be using ` checkbox` not a `radio` since the state is an array.

That said, numbers values in the form state are not currently support. Numeric values has to be strings. 

This is because:
- the `value` attribute of a <input type="checkbox"> is and will always be a string (a `DOMString`)
- it's not safe to assume that some values are going to be numbers.
- And event if they are numbers and I ended up parsing them to numbers, it might not be what users expect or want back. For example, a value may be an area code or a phone number "0011231234", or id that starts with a 0.

To avoid confusing, this library, and many other form libraries, choose to work with strings. It's up to you if you want to cast such values to numbers.

Consider the following as a workaround to achieve what you want:

```js
const Form = ({ onSubmit }) => {
  const [{ values }, { checkbox }] = useFormState<{ status: string[] }>({
    status: [0, 1, 2, 3].map(String),
  });

  const handleSubmit = e => {
    e.preventDefault();
    onSubmit({
      ...values,
      status: values.status.map(Number),
    });
  };

  return (
    <form onSubmit={handleSubmit}>
      {/* 
        as a convenience, you could still pass a number as a value (it'd be silly to
        have to case to a number for each input, so keep in mind these values will 
        be returned as strings in the form state
      */}
      <input {...checkbox('status', 0)} />
      <input {...checkbox('status', 1)} />
      <input {...checkbox('status', 2)} />
      <input {...checkbox('status', 3)} />
      <button>Submit</button>
    </form>
  );
};
```

**Comment by RichardLindhout** [comment]
Another alternative could be the raw input :-)
```
      <Slider
            {...raw('borderRadius')}
            value={values.borderRadius || undefined}
            aria-labelledby="border-radius-changer"
            min={0}
            max={100}
            valueLabelDisplay="on"
          />
```

**Comment by markerikson** [comment]
I'm actually trying to use `raw()` right now, and unfortunately it doesn't seem to work with TS for exactly this reason.

I'm specifically trying to use http://jquense.github.io/react-widgets/api/NumberPicker/ , which really does require a `number` as its value, and its `onChange` passes in just a `number`.

That results in this TS error:

![image](https://user-images.githubusercontent.com/1128784/86393483-236ba080-bc6b-11ea-9ab0-580252a95d15.png)

This is particularly annoying given that the source data field is a number, and I defined my TS form state type as having this field as a number.

**Comment by RichardLindhout** [comment]
@markerikson Actually I had the same thing! I just forgot to update the comment. What I did to overcome the issue was creating a custom component

```
interface FormSliderProps extends Omit<SliderProps, 'onChange'> {
  onChange: (number: number) => any
}
function FormSlider({ onChange, ...rest }: FormSliderProps) {
  const onInnerChange = (e: any, v: number | number[]) => {
    onChange(Number(v) || 0)
  }

  return <Slider {...rest} onChange={onInnerChange} />
}
```

**Comment by markerikson** [comment]
Yeah, I just tried something along the same lines and got this to behave:

```ts
// components/react-widgets.tsx
import React from 'react';
import RWDateTimePicker from 'react-widgets/lib/DateTimePicker';
import RWNumberPicker from 'react-widgets/lib/NumberPicker';

type RWDTProps = React.ComponentProps<typeof RWDateTimePicker>;
type DTProps = Omit<RWDTProps, 'value'> & {
  value?: Date | null;
};

export const DateTimePicker = ({ value, ...otherProps }: DTProps) => {
  return <RWDateTimePicker value={value as any} {...otherProps} />;
};

type RWNPProps = React.ComponentProps<typeof RWNumberPicker>;
type NPProps = Omit<RWNPProps, 'value' | 'onChange'> & {
  value?: number | string;
  onChange?: (value: number) => any;
};

const noop = () => {};

export const NumberPicker = ({ value, onChange = noop, ...otherProps }: NPProps) => {
  const innerOnChange = (value: number = 0) => {
    onChange(value);
  };

  return <RWNumberPicker value={value as any} onChange={innerOnChange} {...otherProps} />;
};


// pages/myPage.tsx
import { DateTimePicker, NumberPicker } from 'components/react-widgets';

interface MyFormState {
  a: number
}

const initialState : MyFormState = {
  a: 0
}

const MyPage = () => {
  const [formState, {raw}] = useFormState<MyFormState>(initialState);

  return <NumberPicker {...raw('a')} />
}
```

That both compiles, and runs correctly, and I can see the actual numbers being stored.
