### ISSUE TITLE
Form re-renders all of it's children even if the value hasn't changed

### ISSUE THREAD

**Issue by ehellman** [wsmd/react-use-form-state#39]
Hi there!

Great job with the lib, however I ran into something when implementing this.

The first this is that I am putting a `console.log` inside each form element to see how many times they re-render. And let's say I have a form like this:

- checkbox 1
- checkbox 2
- radio 1
- radio 2
- radio 3

Every time I click a radio button, all of the elements, including the checkboxes will re-render. Even if I wrap them in `React.memo`. What's the reasoning behind this?

**Comment by ehellman** [comment]
Here is a codesandbox that illustrates the problem:
https://codesandbox.io/s/kk2ln83r97

**Comment by wsmd** [comment]
Thanks for issue @ehellman!

This is definitely something that can be improved.

>  What's the reasoning behind this?

This is happening because the input props for each render rely on the form state itself. Whenever the state changes, the props for all inputs are re-created, but like I said this can be improved! I'm planning on resolve this in the upcoming release 0.9.0.

**Comment by ehellman** [comment]
Ahhhh, at first I thought it had something to do with the `touched` prop, but now I understand what is happening, thanks! :D

Looking forward to testing 0.9.0! :)

**Comment by wsmd** [comment]
> Looking forward to testing 0.9.0! :)

Great! I got started on this and I have a beta version available for testing on npm as of `0.9.0-beta.2`. 

Give it a try by running `npm i react-use-form-state@beta`, and let me know how it goes!

I have a quick demo here too for testing: https://codesandbox.io/s/yq1l6185ox
