### ISSUE TITLE
dynamically add fields

### ISSUE THREAD

**Issue by gentleShark** [wsmd/react-use-form-state#40]
Is it possible to dynamically add fields? If so, would you happen to have an example? If not, it would be a cool enhancement.

**Comment by ehellman** [comment]
You could do something like this: https://codesandbox.io/s/1rj22vwyq7

**Comment by gentleShark** [comment]
> You could do something like this: https://codesandbox.io/s/1rj22vwyq7

Wow, that is an eloquent solution. Thank you, Erik!

**Comment by wsmd** [comment]
Yes! Thank you, @ehellman! Very clever solution! 😄
