### ISSUE TITLE
Using with react-datepicker

### ISSUE THREAD

**Issue by poeti8** [wsmd/react-use-form-state#43]
There are components like [react-datepicker](https://reactdatepicker.com) where their onChange handler is not passing the event object as the first argument. For example, in ReactDatepicker's case, the onChange handler is something like: `(Date, event) => void`.

So when the form handler is trying to access the `e.target.value`, it's going to throw an error, because `target` is undefined.

Maybe the ability to override the onChange handler or to manually set a value would resolve this issue.

**Comment by KaRkY** [comment]
All these forms for onChange should be supported:
onChange(e)
onChange(e, value)
onChange(value)

**Comment by jared-w** [comment]
Does this work? (Adopted from the readme's advanced input section). The functions here are basically just spreading an object into the component with all of the things (value, id, etc) the input needs. [Here's a list of the props DatePicker takes](https://github.com/Hacker0x01/react-datepicker/blob/master/docs/datepicker.md), if they're not called the same you might have to wrap the `text` function and remap some of the property names?

```javascript.jsx
 <DatePicker
        {...text({
          onChange: date => doTheThing(date) /* or (e, value) => {...}, or... */,
          onBlur: () => {} /* Dunno if you'd need to "no op" this */ ,
        })}
      />
```

Remapping should be as simple as defining a `mapProps` function that looks like:

```javascript
function mapProps({prop1, prop2 /* (and so on) */ }) {
  return { newName1: prop1, newName2: prop2, ... } // and so on
}
```

and then using it like `<input {...mapProps(text(...))}`.

**Comment by poeti8** [comment]
No it doesn't. As I said, the problem is that useFormState's handler tries to get the value from `e.target.value` while in this example `e` is undefined. And the onChange handler for helpers like `text()` is not overriding the default onChange behavior, it's just there to help us do side effects.

**Comment by jared-w** [comment]
Ahh, I see now. Sorry for misreading. I thought the onChange was for overriding it, but looking at the source I can see where I missed that. It seems to me that having the `onX` handlers override things would be the most intuitive approach. But the default handler looks quite tightly coupled to the internal mechanisms of the hook... I don't see an immediately obvious fix for that, unfortunately.

**Comment by jwalton** [comment]
I was looking at this exact problem, too (although in my case, the library is `react-select`).

It seems like one solution to this would be to do add some handlers for "raw" types.  Something along the lines of:

```js
export default function SignUpForm() {
  const [formState, { text, raw }] = useFormState();
  return (
    <form onSubmit={() => console.log(formState)}>
      <input {...text('name')} />
      <DatePicker {...raw('date')} />
    </form>
  );
}```

So `raw()` would return, to use some typescript annotation, a:

```ts
interface Raw<T> {
    onChange(date: T): void;
    value: T;
    onBlur(): void;
}
```

?

**Comment by jwalton** [comment]
Although, since I bring up typescript, if we did this, the typescript for the return value of `useFormState` will be... not fun.

**Comment by jwalton** [comment]
Or,

```js
export default function SignUpForm() {
  const [formState, { text, raw }] = useFormState();
  return (
    <form onSubmit={() => console.log(formState)}>
      <input {...text('name')} />
      <DatePicker {...date('date', {raw: true})} />
    </form>
  );
}
```

Although this doesn't work as nicely for this example, since `DatePicker` gives us an actual `Date`, not a string.
