### ISSUE TITLE
Setup formState.validity onMount

### ISSUE THREAD

**Issue by amoebaworks** [wsmd/react-use-form-state#47]
Hi,

Love the lib. One enhancement I'd like to suggest if it is possible: it would be nice if there is a mount useEffect(()=>op(), []) that sets up the initial validity values from the HTML5 input.validity for each input('fieldName'). Currently validity values are set/updated when the user touches the input field.

For example, I have an Add/Edit dialog with a couple of required fields. On Add it is an empty initial state, on Edit the fields are pre-populated. I can't see if the formState is valid until the user clicks on each of the fields. I do not want to assume that if the formState.validity value is missing then it is not valid.

Would only work on formState.values.fieldName that have a corresponding input('fieldName'). For example, the Edit has a DB id I'd like to pass into the formState but not use in the form. I prefer not excluding in the initialState and then later add it back when I have to persist the change. So the on mount validity check would ignore this since there is no input('dbId').

Should work with & without a form tag.

Also maybe a formState.isValid boolean value or function that is true when all formState.validity values are true.

**Comment by wsmd** [comment]
@amoebaworks unfortunately this won't be possible for the time being - not easily. The only way this library is able to access the HTML5 input validity is via the target of the `change` and `blur` events.

This _might_ be possible using refs, but introducing those at this point can be a breaking change, so I'll keep this in mind for when I plan `1.0.0`.

> Also maybe a formState.isValid boolean value or function that is true when all formState.validity values are true.

I think this is a great idea. For the time being it's possible to calculate that using this helper hook:

```js
function useValidateForm(form) {
  return React.useMemo(() => {
    const inputs = Object.keys(form.validity);
    return !!inputs.length && inputs.every(input => form.validity[input]);
  }, [form.validity]);
}

function Form() {
  const [form, inputs] = useFormState();
  const isValid = useValidateForm(form);
  return (
    // ...
  );
}
```
