### ISSUE TITLE
Typescript parameter

### ISSUE THREAD

**Issue by CupCakeArmy** [wsmd/react-use-form-state#51]
First of all: Amazing, tiny lib! No dependencies, native typescript support, this is amazing. Thank you so much! So happy I don't need to code it myself xD 🙏❤️

Small issue with typescript:

```typescript
import React from 'react'
import { useFormState } from 'react-use-form-state'

type Form = {
	name: string
	password: string
}

const SomeForm: React.FC = () => {

	const [form, { text, password }] = useFormState<Form>()

	const _save = async () => {
		console.log(form)
	}

	return <div>
		<input {...text('name')} /> // This throws type error
		<input {...text({ name: 'name' })} /> // Ok
		<input {...password({ name: 'password' })} />
		<button onClick={_save}>Save</button>
	</div>
}

export default SomeForm
```

My tsconfig:
```json
{
  "compilerOptions": {
    "target": "ESNEXT",
    "module": "commonjs",
    "jsx": "react",
     "removeComments": true,
    "noEmit": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "alwaysStrict": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

**Comment by wsmd** [comment]
Thanks a lot, @CupCakeArmy!

I'm not seeing any issues on the latest version.

<img width="603" alt="Screen Shot 2019-04-07 at 11 12 44 AM" src="https://user-images.githubusercontent.com/2100222/55685587-15bf5200-5926-11e9-90a6-a024b5521b7c.png">


What version of `react-use-form-state` are you using in your project?

**Comment by CupCakeArmy** [comment]
Thanks for looking into this so quickly!
Realised I was using typescipt `3.1.6` and upgrading to the lastest solved the issue.

Quick question on the side:
How does one change the input value programmatically, without the initial value. Using ref and setting the value by hand won't work since the onChange event is not getting fired. Any ideas? I did not find anything on the readme
