### ISSUE TITLE
Is redux supported? How?

### ISSUE THREAD

**Issue by dimaqq** [wsmd/react-use-form-state#59]
I'm trying to use this library in the following context:
* there's a record that has many fields
* I'm displaying a form with inputs for these fields
* user would be editing some fields
* async refresh process may change (other or same) field data

I wanted to get to the point where:
* pristine fields would be updated only by async process
* touched fields would be updated only by user

I figured I'd try redux, with data model like so: 
```js
// store state
{ record: {f1: "a", f2: "b", ...},
  overlay: {f2: "bbb", ...}}
// map-to-props
displayed = {...record, ...overlay}
```

At the moment I can't figure out how to marry `react-use-form-state` API to `redux`:
* onChange is pre-field, and happens before state is changed
* issuing redux action directly from `formState` gives me a react warning*

(*)
```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

Am I missing something?
Is this library meant to keep data in component state only?

**Comment by wsmd** [comment]
Hi @dimaqq - `react-use-form-state` is intended to manage form state in the form of a hook - which means it's maintains that state in component itself - it's not intended to be used with other state-management libraries such as Redux.

It might be worth mentioning that react-redux is in the process of introducing hooks APIs: https://github.com/reduxjs/react-redux/releases

Hopefully that will making integrating this library with Redux a bit easier.
