### ISSUE TITLE
StateValues incorrectly typed?

### ISSUE THREAD

**Issue by danielbuechele** [wsmd/react-use-form-state#60]
Why is `type StateValues<T>` an intersection with `{readonly [key: string]: Maybe<string | string[] | boolean>;}`. This allows `formState.validity.fieldThatDoesNotExists`, while removing the intersection type, this would throw an error. Is there any case, where the object would have keys that are not `keyof T`?

https://github.com/wsmd/react-use-form-state/blob/master/src/index.d.ts#L48

PS: Since the type definitions were recently updated, can you release a new version.

**Comment by wsmd** [comment]
Thanks for the issue @danielbuechele!

Ha! Looks like this is some "leftovers" from before the refactor/improvements I made here a while ago (around v0.6.2): https://github.com/wsmd/react-use-form-state/pull/28/files#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8

Good catch. I think I can clean it up a bit more. This might be no longer needed.

**Comment by wsmd** [comment]
> PS: Since the type definitions were recently updated, can you release a new version.

I'm holding off the next release, 0.10.0, until I get a few things off my list.

I'll publish a new release very soon. Hopefully by Monday.

**Comment by wsmd** [comment]
**Quick Update**

I published a fix for this in `0.9.1` 👍 

Thanks again for the issue _and_ the PR :)
