### ISSUE TITLE
TypeError: raw is not a function

### ISSUE THREAD

**Issue by stclairdaniel** [wsmd/react-use-form-state#69]
I am using a custom AutoComplete extending `react-select` like so:
`    const [formState, { raw, select }] = useFormState({ members: [] });`

`<AutoComplete
                ...
                {...raw({ name: 'members' })}
/>`

And getting the following error:
`Error: Uncaught TypeError: raw is not a function  Script: http://localhost:3000/static/js/1.chunk.js, Line: 174414, Column: 5 TypeError: raw is not a function
    at AddToGroupForm (AddToGroupForm.jsx:84)`

Is this perhaps user error? I'm trying to get this working with multiSelect - single select with my component and `select` works just fine, but I seem to need `raw` in order to capture the changes for multi.

**Comment by stclairdaniel** [comment]
I'm so sorry - I was using outdated code. Please ignore this.

**Comment by wsmd** [comment]
Hi @stclairdaniel – sorry for the confusion.

`raw` will be added in `0.10.0` which isn't released yet (I'm planning on releasing that later today).

The documentation on the GitHub master branch is for the next version. Please refer to this branch https://github.com/wsmd/react-use-form-state/tree/0.9.1 for the `latest` documentation.

**Comment by stclairdaniel** [comment]
Thanks for the quick reply! Our team has been loving the library so far - looking forward to implementing raw to work with react-select :)

**Comment by wsmd** [comment]
That said, I'm actually looking for beta testers if you are interested – `raw` is currently available in the beta release `react-user-form-state@beta`.

**Comment by stclairdaniel** [comment]
I'd love to but we've made a local version with some specific changes - I'll talk to my team about creating a fork here with our changes.

Is this an ok place to ask for some help with `selectMultiple`? There's nothing in the docs about how to use it, but I don't understand how to pass in the options - I'm getting an error `TypeError: Cannot convert undefined or null to object` here:
`function getNextSelectMultipleValue(e) {
  109 | 
> 110 |     return Array.from(e.target.options).reduce(`

I don't see where `options` is being supplied to the target - am I suppose to do this manually?

**Comment by wsmd** [comment]
> I don't see where options is being supplied to the target - am I supposed to do this manually?

`options` is a native DOM attribute of `HTMLSelectElement` (aka `<select>`). This option represents the options that are set manually - so yes, you have to set the options manually.


```js
function App() {
  const [formState, { selectMultiple }] = useSelect();
  return (
    <select {...selectMultiple('items')}>
      <option value="a">Item A</option>
      <option value="b">Item B</option>
      <option value="c">Item C</option>
    <select>
  );
}
```

I hope that helps.
