### ISSUE TITLE
Validate all inputs without touch

### ISSUE THREAD

**Issue by poeti8** [wsmd/react-use-form-state#82]
So imagine a scenario where a user clicks on the submit button without touching any of the fields, and since `formState.validity` object is empty, I am not able to verify the fields and also can't show the correct error message for each of them. 

I think all of the fields should run the validation method on each render. There also could be a function to validate all the fields so we can use it in submissions.

**Comment by adjourn** [comment]
These might help you: #57 #47 #56

**Comment by poeti8** [comment]
Nope didn't help that much. But I'm going to close this issue because it's duplicated.
