### ISSUE TITLE
Cannot read property 'valid' of undefined 

### ISSUE THREAD

**Issue by xeastcrast** [wsmd/react-use-form-state#83]
When i use select.
onChange event I get this error in log.

```
**Cannot read property 'valid' of undefined** 
```

**Comment by xeastcrast** [comment]
Select type can use only native select element right?
I use it with Material-UI React, And not work!

**Comment by kwhitley** [comment]
@wsmd I'm undergoing the same struggles when trying to implement this with `@material-ui/core/Slider` - no matter which input type I use (`range` seems the most appropriate), there appears to be a problem with how the refs are handled, or the onChange signature or something...
