### ISSUE TITLE
Extend `FormOptions` to receive global `validateOnBlur` value

### ISSUE THREAD

**Issue by melloc01** [wsmd/react-use-form-state#89]
It'd be useful to set a global validateOnBlur method, validating on every input makes code a little noisy.

By the way, the real problem is that I am having some perf issues on a big form and adding validateOnBlur is making the form much lighter.

I can try to reprocude in a code sandbox and open another issue but nevertheless a global `validateOnBlur` would make sense for the lib I think

**Comment by wsmd** [comment]
This will be coming in 0.12.0! so sit tight until then! :D

**Comment by wsmd** [comment]
This issue is now fixed in `v0.12.0`! 🎉
