### ISSUE TITLE
Joi browser for form input schema validation

### ISSUE THREAD

**Issue by ducdev** [wsmd/react-use-form-state#9]
I think it would make sense for this integration. How do you think ?
https://github.com/hapijs/joi

**Comment by davej** [comment]
I think it would be better to let the user choose custom validation. I use `yup` for validation for example.

**Comment by wsmd** [comment]
Thanks for the great suggestion @ducdev, @davej.

Closing this issue in favor of #16 which has an alternative solution to custom validation.
