### ISSUE TITLE
Uncaught TypeError: formState.setFieldError is not a function

### ISSUE THREAD

**Issue by lichtcui** [wsmd/react-use-form-state#90]
const setError = () => formState.setFieldError('text', 'aaaaa')

"react-use-form-state": "0.10.4"
Uncaught TypeError: formState.setFieldError is not a function

the setFieldError doesn't work...

**Comment by wsmd** [comment]
Hi @lichtcui - the method `setFieldError` was added recently and is planned to be included in the next release `0.11.0` once it's published. The current stable version is `0.10.4`.

For the time being, you can use `0.11.0-beta.1`, or refer to this URL for the proper documentation of the current version you are currently using: https://github.com/wsmd/react-use-form-state/tree/0.10.4

**Comment by lichtcui** [comment]
thanks~~~
