### ISSUE TITLE
Question: Tel format masking?

### ISSUE THREAD

**Issue by dstroot** [wsmd/react-use-form-state#92]
Anyone using https://www.npmjs.com/package/react-text-mask to mask a field like a phone number?  I am trying to figure out how to best handle a phone number field that needs to filled out with an int'l number format.   

It would be super powerful if I could figure out how to integrate this hook with this capability: https://text-mask.github.io/text-mask/ 

Any ideas/suggestions?

**Comment by wsmd** [comment]
Hi @dstroot - sorry for the late response. 

I hope you found a way around this issue, but if you're still looking for help, I'd suggest looking into utilizing `raw` which allows you to [build custom controls](https://github.com/wsmd/react-use-form-state#custom-controls) with different interfaces (it's sort of an adapter).

I'm not really familiar with that component you linked above, but perhaps you could build a wrapper component around your masked input and let this hook communicate with it using the `raw` type.

Something along these lines:

```jsx
function MyMaskedInput({ onChange, onBlur, value, name }) {
  return (
    <MaskedInput
      name={name}
      mask={[/* ... */]}
      onChange={/* ... */}
      onBlur={/* ... */}
    />
  )
}

function Form() {
  const [formState, { raw }] = useFormState();
  return (
    <div>
      <MaskedInput {...raw('phone')} />
    </div>
  )
}
```

**Comment by dstroot** [comment]
Actually seems even easier new that I am trying it - <MaskedInput/> can be used as a direct replacement for <input />
