### ISSUE TITLE
Can't set error from the onChange handler

### ISSUE THREAD

**Issue by steliyan** [wsmd/react-use-form-state#96]
I have a form `onChange` handler that sends the data to a backend. Based on that response, a field may become invalid.

Here is the sample code:
```javascript
const saveFieldAsync = (name, value) => {
  const req = createRequest(name, value);
  axios(req).catch(e => {
    // I need to update the form state for the invalid field
  });
};

const [formState, formInputs] = useFormState(null, {
  onChange: ({ target: { name, value } }) => saveFieldAsync(name, value),
});
```

However, in order to do that I need the `setFieldError` passed to `onChange`. Technically, this is possible if you don't have a form-wide `onChange` but you attach manually an `onChange` handle for each input.

Here is the simplest solution I could come up with:
https://github.com/steliyan/react-use-form-state/commit/f359f7b97f376ee69b8f0e1b7c203fc275f75321

I've tried making the `formOptions` to accept a `function` instead of an `object`, but the code got really ugly. You have a better understanding of the code, I'm pretty sure you can come with something better than me.

And last but not least, congrats on your work on this library! :)

Greetings, Steliyan.

**Comment by wsmd** [comment]
Hi @steliyan, sorry for the delay and thank for your patience! :)

Have you considered passing the formState as argument to the `saveFieldAsync`?

```js
function saveFieldAsync(name, value, formState) {
  const req = createRequest(name, value);
  axios(req).catch(err => {
    formState.setFieldError(name, err);  // <--
  });
}

function MyForm() {
  const [formState, formInputs] = useFormState(null, {
    onChange: ({ target: { name, value } }) => {
      saveFieldAsync(name, value, formState); // <--
    },
  });

  return /* ... */
}
```

**Comment by steliyan** [comment]
This should work!
