### ISSUE TITLE
Can't find  setFieldError method in formState

### ISSUE THREAD

**Issue by huurray** [wsmd/react-use-form-state#97]
ver 0.10.4

hello, i had to set error at particular situation. so  i read Doc and found setFieldError(setFieldError(name: string, error: string): void) Function.
but i couldn't find setFieldError method in the code

can you check for me? my version is resent

**Comment by gentleShark** [comment]
@huurray yes, it appears the current release is actually 10.1. you can add the master repo as a dependency in your package.json andt then you have to run the build scripts for react-use-form-state. I ran into errors after building so a couple weeks back so I ended up not using setFieldError which I was considering adding to a submit function. Looking forward to the release of setFieldError.

**Comment by huurray** [comment]
@gentleShark i understand! thanks for answering!

**Comment by wsmd** [comment]
Hi @huurray @gentleShark setFieldError isn't published yet - I'll do my best to publish it this early week. In the meantime please refer to this comment: https://github.com/wsmd/react-use-form-state/issues/90#issuecomment-506434867
