### ISSUE TITLE
invalid hook call

### ISSUE THREAD

**Issue by keeganstothert** [wsmd/react-use-form-state#98]
i'm getting this error on this `Invalid hook call. Hooks can only be called inside of the body of a function component. `

my usage is dead simple so not sure why this is happening

```js
export default function Login() {
  const [formState, { email, password }] = useFormState();

  return (
    <form>
      <input {...email('email')} />
      <input {...password('password')} />
    </form>
  );
}
```

**Comment by wsmd** [comment]
Hi @keeganstothert - any chance you can share a repo reproducing this issue that I can look at?

I’d also suggest trying React’s own hooks (e.g. `useState`) and see if the same issue occurs. It might have something to do with your project’s setup.

**Comment by keeganstothert** [comment]
`rm -rf node_modules && npm i` is the web equivalent of "have you tried turning it off and on again?"...anyway just did that and the error went away. Thanks for the quick response
